AtomicFinance/atomic-utils

packages/logger/__tests__/logger/logger.spec.ts, packages/logger/lib/transports/sentry-transport.ts
This PR fixes sentry init node options
=> Fix sentry init node options

packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json, yarn.lock
=> ⬆️: Bump node-dlc to 0.18.3

package.json, packages/time/README.md, packages/time/__tests__/time-utils/time-utils.spec.ts, packages/time/__tests__/tsconfig.json, packages/time/lib/index.ts, packages/time/lib/interfaces/IStrategy.ts, packages/time/package-lock.json, packages/time/package.json, packages/time/tsconfig.json, yarn.lock
This PR extracted duplicated time + strategy event utilities from projects such as `kiwi-bot` and `dlc-notification-server` into the `time` utility package.
To follow DRY principles, and reduce duplicated logic and refactoring costs.
This allows our various projects to use the same logic, and avoid bugs encountered by divergent implementation.
=> feat(time): extract time utility functions

packages/clients/README.md, packages/clients/__tests__/fixtures/oracleResponses.ts, packages/clients/__tests__/oracle/oracle-client.spec.ts, packages/clients/__tests__/tsconfig.json, packages/clients/lib/index.ts, packages/clients/lib/oracle/client.ts, packages/clients/lib/oracle/options.ts, packages/clients/package-lock.json, packages/clients/package.json, packages/clients/tsconfig.json
Oracle Client for querying oracle service
=> ✨feat: oracle client for querying oracle service

packages/clients/__tests__/fixtures/strategyResponses.ts, packages/clients/__tests__/strategy-client.spec.ts/strategy-client.spec.ts, packages/clients/lib/index.ts, packages/clients/lib/oracle/client.ts, packages/clients/lib/strategy/client.ts, packages/clients/lib/strategy/options.ts, packages/clients/package-lock.json
Create client for querying strategy service. 
Used for ENG-952 (kiwi-bot) and OptionsApp in the future.
=> ✨ feat: client for querying strategy service

packages/clients/__tests__/strategy-client.spec.ts/strategy-client.spec.ts, packages/clients/lib/strategyClient.ts
Switch data params (start date and end date) to sanke case for strategy service client
=> 🐛 fix: date params to snake case strategy service

packages/clients/__tests__/strategy-client.spec.ts/strategy-client.spec.ts, packages/clients/lib/strategyClient.ts
Switch back to camelcase input for strategy client
=> ♻️ refactor: switch to camelcase strategy client

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
Move trading open half month 2 hours earlier
=> 🐛 fix: move trading open half month earlier

packages/clients/lib/oracleClient.ts
Add outcome to announcement response for oracle client
=> 🐛 fix: add outcome to announcement response oracle

packages/clients/lib/baseClient.ts
Improve error handler for react native
=> ✨ feat: improve error handler for react native

packages/clients/lib/baseClient.ts, packages/clients/lib/index.ts
=> ✨ feat: export base client

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
Add `findCycleMaturityMonthsInPast` and `findNumCyclesInPastMaturityExists` for finding a maturity x months in past and finding how many months in past a maturity is respectively
=> ✨ feat: add functions for finding maturity in past

packages/clients/__tests__/fixtures/strategyResponses.ts, packages/clients/lib/strategyClient.ts
- Add `apy_all` field to strategy state response
=> ✨ feat: add `apy_all` field to stratgey state

packages/clients/__tests__/oracle/oracle-client.spec.ts, packages/clients/lib/oracleClient.ts, packages/clients/lib/strategyClient.ts
Add `getAnnouncementByAnnouncementId` and remove unnecessary `async`
=> ✨ feat: add `getAnnouncementByAnnouncementId`

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
=> ✨ feat: Add isHalfMonth util

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
Port over the backtester's CSO util function `getUpcomingFriday`
=> ✨ feat: add `getUpcomingFriday` util

packages/clients/__tests__/fixtures/strategyResponses.ts, packages/clients/lib/strategyClient.ts
Add fields for `max_drawdown_percentage` / `max_drawdown_duration` and `created_at` / `updated_at`
=> ✨ feat: add fields for drawdown and updated at

packages/clients/lib/baseClient.ts, packages/clients/lib/options.ts
Add default timeout for clients
=> ✨ feat: add default timeout for clients

packages/clients/__tests__/fixtures/strategyResponses.ts, packages/clients/lib/strategyClient.ts
Add longest gap duration to strategy state response
=> ✨ feat: longest gap duration strategy state response

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> ⬆️ upgrade: node-dlc to 0.21.1

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> ⬆️ upgrade: node-dlc to 0.21.2

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
Add `getCsoLength` function to cso lib to get the length from oracle announcement event id
=> ✨ feat: add get cso length

packages/clients/__tests__/fixtures/strategyResponses.ts, packages/clients/lib/strategyClient.ts
Add TLV and max capacity to strategy client
=> 🏷️ types: add tvl and max capacity to strategy client

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
Add `getPreviousFriday` function to accompany `getUpcomingFriday` function
=> ✨ feat: add getPreviousFriday fn

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> ⬆️ upgrade: node-dlc to 0.22.4

packages/time/__tests__/time-utils/cso-utils.spec.ts, packages/time/lib/cso.ts
Fix timezone issue cso event id parse UTC
=> fix: timezone issue cso event id parse utc

packages/time/lib/cso.ts
Fix timezone issue cso event id parse new entry closed
=> fix: timezone issue cso event id parse new entry closed

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> dep-up: node-dlc 0.23.2

justfile
=> config: add justfile

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> dep-up: node-dlc 0.23.3

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> dep-up: node-dlc 0.23.4

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> dep-up: node-dlc 0.23.5

packages/clients/lib/strategyClient.ts
Add Strategy Trade Data to StrategyStateResponse
=> feat: add strategy trade data to strategy state response

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/logger/package-lock.json, packages/logger/package.json
=> dep-up: node-dlc 0.23.6

packages/clients/package-lock.json, packages/clients/package.json, packages/contract/package-lock.json, packages/contract/package.json, packages/deribit/package-lock.json, packages/deribit/package.json, packages/format/package-lock.json, packages/format/package.json, packages/logger/lib/transports/sentry-transport.ts, packages/logger/package-lock.json, packages/logger/package.json, packages/time/package-lock.json, packages/time/package.json
Update https://github.com/AtomicFinance/node-dlc to 0.24.0
=> chore: update @node-dlc deps to 0.24.0

packages/clients/package.json, packages/deribit/package.json, packages/logger/package.json, pnpm-lock.yaml
=> dep-up: @node-dlc 1.1.1
